---
title: "ST502 HW6 - Bayesian Project"
author: "Charles Lane"
format: html
editor: visual
---

## Task 1 - Read-in Data

> Begin by reading in the diabetes data, which is included in this repository.

```{r}
d_data = read.csv('diabetes-dataset.csv')
head(d_data)
```

> create a matrix to fill with iterated B0, B1 values.

```{r}
g_mat <- matrix(NA, nrow=6000,ncol = 2)
head(g_mat)
```
### Determine regression variables

```{r}
#############################################
##Page 98-101 code
#############################################

#Create Uniform Prior function to show the process for having a prior in a function
prior = function(theta){
  if((theta < 0) || (theta > 1)){ 
    return(0)
  }else{
    return(1)
  }
}

#Binomial distribution for y|theta (ignoring the constant wrt theta)
likelihood = function(theta, y,n){
  return(theta^(y) * (1-theta)^(n-y))
}

#Create a function that takes in an observed y, sample size n, number of iterations to run and 
#starting values for parameter theta and the "jumping distribution's" sd
thetasampler <- function(y, n, niter, thetastartval, thetaproposalsd){
  
  #vector to store sampled theta's
  theta <- rep(0 , niter)
  #use the starting value as the first theta
  theta[1] <- thetastartval
  
  #loop through the desired number of iterations
  for(i in 2:niter){
    #temporary value for current theta is previous theta
    currenttheta <- theta[i-1]
    
    #get the next random draw 
    newtheta <- currenttheta + rnorm(1, 0, thetaproposalsd)
    
    #Find r ratio: 
    r <- prior(theta = newtheta)*likelihood(theta = newtheta, y = y, n = n)/
      (prior(theta = currenttheta)*likelihood(theta = currenttheta, y = y, n = n))
    
    #accept this new value with prob min(1,r)
    if(runif(1)<r){
      theta[i] <- newtheta      # accept move with probabily min(1,r)
    } else {
      theta[i] <- currenttheta  # otherwise "reject" move, and stay where we are
    } #end if's
  } #end loop 
  #return the vector of theta values	
  return(theta)
} #end function

# running this sample for y=13, n = 20.
randomDraws <- thetasampler(y = 13, 
                            n = 20,
                            niter = 50000,
                            thetastartval = 0.1,
                            thetaproposalsd = 0.1)

```


### Bayesian Calculation

```{r}
#################################################
##Page 88-92
##Computing bayesian estimates and credible intervals
###################################################

#sample size
n<-50
#Set alpha/beta for prior that is uniform
alpha <- 1
beta <- 1
#Set alpha/beta for prior that is informative
# alpha <- 20
# beta <- 2

#number of successes
y <- 3

par(mfrow = c(1, 2))
#Plot means of poseteriors
#First a plot of the prior density
curve(dbeta(x, 
            shape1 = alpha,
            shape2 = beta),
      main = paste("Prior~Beta(", alpha, ",", beta, ")", sep = ""),
      xlab = "theta",
      ylab = "f(theta)",
      ylim = c(0,1.2))
abline(v = alpha/(alpha+beta),
       lwd = "3",
       col = "Green")
legend(x = "topleft",
       col = c("green"), 
       legend = c("Prior Mean"),
       pch = 10)

#Plot of the posterior
curve(dbeta(x,
            shape1 = alpha + y,
            shape2 = beta + n - y),
      main = paste("Posterior with (theta-hat=", 
                   round(y/n, 3), ",\nn=", n, ")", sep=""),
      xlab = paste("theta  Posterior Var =", 
                   round((alpha + y)*(beta + n - y)/((alpha + beta + n)^2*(alpha + beta + n + 1)), 5), 
                   sep = ""),
      ylab = "f(theta|y)")
abline(v = alpha/(alpha+beta),
       lwd = "3",
       col = "Green")
abline(v = y/n,
       lwd = "2",
       col = "Blue")
abline(v = (alpha + y)/(alpha + beta + n),
       lwd = "2",
       col = "Black")
legend(x = "topright",
       col = c("Green", "Blue", "Black"),
       legend = c("Prior Mean", "Sample Mean", "Posterior Mean"),
       pch = 15)


#Set alpha/beta for prior that is informative
alpha <- 20
beta <- 2

#number of successes
y <- 3

par(mfrow = c(1,2))
#Plot means of poseteriors
#First a plot of the prior density
curve(dbeta(x, 
            shape1 = alpha,
            shape2 = beta),
      main = paste("Prior~Beta(", alpha, ",", beta, ")", sep = ""),
      xlab = "theta",
      ylab = "f(theta)")
abline(v = alpha/(alpha+beta),
       lwd = "3",
       col = "Green")
legend(x = "topleft",
       col = c("green"), 
       legend = c("Prior Mean"),
       pch = 10)

#Plot of the posterior
curve(dbeta(x,
            shape1 = alpha + y,
            shape2 = beta + n - y),
      main = paste("Posterior with (theta-hat=", round(y/n, 3), ",\nn=", n, ")", sep=""),
      xlab = paste("theta  Posterior Var =", round((alpha + y)*(beta + n - y)/((alpha + beta + n)^2*(alpha + beta + n + 1)), 5), sep = ""),
      ylab = "f(theta|y)")
abline(v = alpha/(alpha+beta),
       lwd = "3",
       col = "Green")
abline(v = y/n,
       lwd = "2",
       col = "Blue")
abline(v = (alpha + y)/(alpha + beta + n),
       lwd = "2",
       col = "Black")
legend(x = "topright",
       col = c("Green", "Blue", "Black"),
       legend = c("Prior Mean", "Sample Mean", "Posterior Mean"),
       pch = 15)
```

